config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get "about", to: "pages#about"
  
  resources :users
  get 'providers/search', to: 'providers#search'
  resources :providers, only: [ :index, :show, :edit, :update, :destroy ]
  resources :my_providers
  delete "my_providers/unselect/:id", to: "my_providers#unselect"

  resources :moves do
    resources :updates, only: [ :index, :edit ]
  end

  post "start", to: "updates#create_updates"
  post "send", to: "updates#send_updates"
  get "pdfs/:uuid", to: "pdfs#show", as: "pdf"
  get "pdfs/:uuid/mail", to: "pdfs#mail", as: "mail"

  # What's this for? Nicer dashboard URL?
  get '/user' => "my_providers#index", :as => :user_root
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">

  <ul class="list-unstyled list-inline text-center">
    <li class="list-inline-item">
      <a href="https://www.facebook.com" class="btn-floating btn-fb mx-1">
        <i class="fab fa-facebook-f"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a href="https://www.twitter.com" class="btn-floating btn-tw mx-1">
        <i class="fab fa-twitter"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a href="https://www.instagram.com" class="btn-floating btn-li mx-1">
        <i class="fab fa-instagram"> </i>
      </a>
    </li>

    <li class="list-inline-item">
       © 2020 Copyright: AddressMover <i class="fas fa-heart"></i>
    </li>
  </ul>

  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= yield(:navbar_class) %>">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logos/option-white-text.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="d-flex align-items-center navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "My Dashboard", my_providers_path(checked:"1"), class: "nav-wagon-link " %>
        </li>
        <li>
          <a href="https://address-mover-trucks.herokuapp.com" target="_blank">Moving helpers</a>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatar.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
             <%= link_to "Update Profile", edit_user_registration_path, class: "dropdown-item" %>
             <%= link_to "About", about_path, class: "dropdown-item" %>
             <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "login nav-wagon-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>