config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get "about", to: "pages#about"
  
  resources :users
  get 'providers/search', to: 'providers#search'
  resources :providers, only: [ :index, :show, :edit, :update, :destroy ]
  resources :my_providers
  delete "my_providers/unselect/:id", to: "my_providers#unselect"

  resources :moves do
    resources :updates, only: [ :index, :edit ]
  end

  post "start", to: "updates#create_updates"
  post "send", to: "updates#send_updates"
  get "pdfs/:uuid", to: "pdfs#show", as: "pdf"
  get "pdfs/:uuid/mail", to: "pdfs#mail", as: "mail"

  # What's this for? Nicer dashboard URL?
  get '/user' => "my_providers#index", :as => :user_root
end

app/views/pages/_about-banner.html.erb
<div class="container-about">
  <div class="about-picture"></div>

  <div class="about-text">
    <h3><strong>About AddressMover</strong></h3>
    <hr>
    <p>For most of us, moving is a stressful event. You have to deal with a new home, a new commute, a new neighborhood or even just an unfamiliar location. It's time-consuming and can be expensive. We started AddressMover from a simple idea helping people who are moving save time and money. And if in the meantime we make their lives a little easier and less stressful, even better.</p>
    <p>The process of moving can be long and complicated. You have to move out of your old house and go through the process of transforming your house into your home. It's a lot to do - and it's not always cheap.</p>
    <p>With AddressMover you change your address for all your service providers with only a few clicks.AddressMover is free, secure and easy to manage.</p>
  </div>
</div>

app/views/pages/_home-banner.html.erb
<div class="banner">
    <div class="banner-content text-left">
      <h1>The future of moving is here.</h1>
      <p>With AddressMover change your address for all your service providers with only a few clicks.</p>
      <%= link_to "Start Now", my_providers_path, class: "btn btn-lg btn-primary"  %>
    </div>
</div>

app/views/pages/_home-middle-text.html.erb
<div class="container my-5">

  <div class="row mx-5 row justify-content-center mx-5 my-5">
    <div class="text-center home-center-text">
      <h2>AddressMover is free, secure and easy to manage.</h2>
      <h2>How does it work?</h2>
    </div>
  </div>

  <div class="steps-row row my-5">


    <div class="col text-center home-steps">
      <i class="fas fa-user-plus"></i>
      <h2>Share your move</h2>
      <p> Planning to move? Start by letting us know your new address and moving date.<br> Easy as that.</p>
    </div>
     </div>
<div class="steps-row row my-5">

    <div class="col text-center home-steps">
      <i class="fas fa-search-plus"></i>
      <h2>Choose your services</h2>
      <p>Select providers you want us to inform about your address change.<br> No more struggling.</p>
    </div>
  </div>
  <div class="steps-row row my-5">


    <div class="col text-center home-steps">
      <i class="fas fa-flag-checkered"></i>
      <h2>You are ready!</h2>
      <p>Start the update and check the status on your dashboard.<br> Stay ahead of things.</p>
    </div>
</div>


</div>

app/views/pages/_home-providers-layout.html.erb
<div class="home-providers-layout my-5 p-5">
  <div class="container d-flex">
  <h3> Check out some of the services we work with :</h3>
</div>
  <div class="container d-flex justify-content-center">
    <%= render "providers/cards-index" %>
  </div>
  <div class="container d-flex justify-content-center">
    <%= link_to "Go to All Services", providers_path, class: "btn btn-lg" %>
  </div>
</div>

app/views/pages/_join-us-layout.html.erb
<div class="container join-us-layout my-5 p-5 text-center">
  <% if user_signed_in? %>
    <h4> Stressed about having to update your info when you move?</h4>
    <h4>Start today and change your address in all your services in minutes!</h4>
    <div class="container d-flex justify-content-center">
      <%= link_to "Create a Move", new_move_path, class: "btn btn-lg btn-success my-3" %>
    </div>
  <% else %>
    <h4> Stressed about having to update your info when you move?<br> Register in two minutes and get started today!</h4>
    <div class="container d-flex justify-content-center">
      <%= link_to "Join Us", new_user_registration_path, class: "btn btn-lg btn-success my-3" %>
    </div>
  <% end %>
</div>

app/views/pages/_testimonials.html.erb
<div class="container text-center">
   <h2> What our customers say about us : </h2>
<div class="testimonials">

    <div class="card">
        <div class="layer"></div>
        <div class="content">
            <i class="fas fa-quote-right"></i>
            <p>
                A friend told me about this just before my move to Dresden. I can't believe how smooth it worked. Great free service, the process is simple and went super fast!</p>
            <div >
                  <%= image_tag "avatar2.jpg", class: "image" %>
            </div>
             <div class="details">
                <h2>Milena G.<br><span>Dresden</span></h2>
             </div>
        </div>
    </div>
    <div class="card">
        <div class="layer"></div>
        <div class="content">
            <i class="fas fa-quote-right"></i>
            <p>
                Tried it and worked best, it was always very stressful to have to change info on each of the services I use. I will be more than happy to use it again very soon.</p>
            <div >
               <%= image_tag "avatar3.jpg", class: "image" %>
            </div>
            <div class="details">
                <h2>Alex A.<br><span>Berlin</span></h2>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="layer"></div>
        <div class="content">
            <i class="fas fa-quote-right"></i>
            <p>
               Very easy process, I can keep a list of all my services and use them on my next moves if I want. Has helped me a lot since I am always moving because of my job.
            </p>
            <div >
              <%= image_tag "avatar4.png", class: "image" %>
            </div>
            <div class="details">
              <h2>Miluska S.<br><span>Freiburg</span></h2>
            </div>
        </div>
      </div>
    </div>
  </div>

app/views/pages/about.html.erb
<div class="container my-3">

  <%= render 'about-banner' %>

</div>

app/views/pages/home.html.erb
<%= content_for(:navbar_class, "navbar-home") %>

<%= render 'home-banner' %>

<%= render 'home-middle-text' %>

<%= render 'home-providers-layout' %>

<%= render 'testimonials' %>

<%= render 'join-us-layout' %>