config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get "about", to: "pages#about"
  
  resources :users
  get 'providers/search', to: 'providers#search'
  resources :providers, only: [ :index, :show, :edit, :update, :destroy ]
  resources :my_providers
  delete "my_providers/unselect/:id", to: "my_providers#unselect"

  resources :moves do
    resources :updates, only: [ :index, :edit ]
  end

  post "start", to: "updates#create_updates"
  post "send", to: "updates#send_updates"
  get "pdfs/:uuid", to: "pdfs#show", as: "pdf"
  get "pdfs/:uuid/mail", to: "pdfs#mail", as: "mail"

  # What's this for? Nicer dashboard URL?
  get '/user' => "my_providers#index", :as => :user_root
end

app/models/pdf.rb
class PDF < ApplicationRecord
  # belongs_to :update
  # NB: can't do the above, it conflicts with .update method
  # We'll be using .parent to refer to its Update
  belongs_to :parent, foreign_key: "update_id", class_name: "Update"

  def url
    # host must be set in the development/production.rb
    Rails.application.routes.url_helpers.pdf_url("#{uuid}.pdf")
  end
end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  def show
    skip_authorization

    @pdf = PDF.find_by(uuid: params[:uuid])
    raise ActionController::RoutingError.new('Not Found') if @pdf.nil?

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Address Change Notification",
               # disposition: 'attachment', # default 'inline'
               margin: { top: 20, bottom: 25, left: 25, right: 20 }
      end
    end
  end

  def mail
    @pdf = PDF.find_by(uuid: params[:uuid])
    raise ActionController::RoutingError.new('Not Found') if @pdf.nil?
    authorize @pdf

    LetterSendJob.set(wait: 5.seconds).perform_later(@pdf.parent)
    SmsSendJob.perform_later(@pdf.parent)

    redirect_to my_providers_path, notice: "We're sending the letter to #{@pdf.parent.provider.name} 📧. You will receive a confirmation via SMS."
  end
end

app/views/pdfs/show.html.erb
<div class= "pdf-cont">
  <div class="picture"></div>
  <div class="pdf-body">
    <h2 class="pl-3"><strong>Post Notification</strong> <i class="fas fa-envelope-open-text"></i></h2>

    <div class="card-group">
      <div class="card card-pdf col-5 p-3 m-3">
        <div class="card-header bg-white border-0">
          <h3><strong>Send it yourself</strong></h3>
        </div>
        <div class="card-body">
          <p>
              Looks like <strong><%= @pdf.parent.provider.name %></strong> did not accept the request.
              <%= icon("fas", "heart-broken", class:"heart") %>
          </p>
          <p>
              This time they need a paper letter with your change request.
          </p>
          <p>
              Just download this PDF we made for you, print it, and send it by post.
          </p>
        </div>
        <div class="card-footer bg-transparent border-success">
              <%= link_to "Download letter", pdf_path("#{@pdf.uuid}.pdf"), class: "btn btn-primary" %>
        </div>
      </div>
      <div class="card card-pdf col-5 p-3 m-3">
        <div class="card-header bg-white border-0">
          <h3><strong>Let us send it for you</strong></h3>
        </div>
        <div class="card-body">
          <p>
            Or even better - <strong>we can send it for you</strong>! Isn't it awesome? 
            The first letter is on us
            <%= icon("fas", "grin-stars", class: "text-success") %>
          </p>
          <p>
            It will be sent to:<br>
            <p> <strong> <%= @pdf.parent.provider.name %> </strong> <br>
              <%= "#{@pdf.parent.provider.street_name} #{@pdf.parent.provider.street_number}" %>
              <br>
              <%= "#{@pdf.parent.provider.zip} #{@pdf.parent.provider.city}" %>
            </p>
          </p>
        </div>
        <div class="card-footer bg-transparent border-success">
          <%= link_to "Send the letter", mail_path(@pdf.uuid), class: "btn btn-primary" %>
        </div>
        </div>
      </div>
      <%= link_to "Back to Dashboard", my_providers_path , class:"pl-3" %>
    </div>
  </div>
</div>

app/views/pdfs/show.pdf.erb
<meta charset="utf-8" />

<style>
  body {
    font-family: "Times New Roman", Times, serif;
    font-size: 18px;
  }

  .pdf-sender-right {
    text-align: right;
    margin-bottom: 125px;
  }

  .pdf-recipient-left {

  }

  .pdf-h2 {
    margin-bottom: 50px;
  }

  .pdf-date-right {
    text-align: right;
    margin-top: 75px;
    margin-bottom: 50px;
  }

  .pdf-address {
    font-weight: bold;
  }
  .pdf-greetings-bottom {
    margin-top: 50px;
  }
</style>


<div class="pdf-sender-right">
  <p> <%= @pdf.parent.move.user.full_name %> </p>
  <p>
    <%= "#{@pdf.parent.move.street_name} #{@pdf.parent.move.street_number}" %>
    <br>
    <%= "#{@pdf.parent.move.zip} #{@pdf.parent.move.city}" %>
  </p>
</div>

<div class="pdf-recipient-left">
  <p> <strong> <%= @pdf.parent.provider.name %> </strong> </p>
  <p>
    <%= "#{@pdf.parent.provider.street_name} #{@pdf.parent.provider.street_number}" %>
    <br>
    <%= "#{@pdf.parent.provider.zip} #{@pdf.parent.provider.city}" %>
  </p>
</div>

<div class="pdf-date-right">
  <%= DateTime.now.strftime("%d/%m/%Y") %>
</div>

<h2 class="pdf-h2">
  Adressänderung wegen Umzug
</h2>

<p>
  Sehr geehrte Damen und Herren,
</p>
<p>
  hiermit teile ich Ihnen folgende Änderung meiner Wohnanschrift mit. Die Änderung ist gültig
  ab dem <%= @pdf.parent.move.moving_date.strftime("%d/%m/%Y") %>.
</p>
<p>
  Die neue Anschrift lautet:
</p>

<div class="pdf-address">
  <p>
    <%= "#{@pdf.parent.move.street_name} #{@pdf.parent.move.street_number}" %>
    <br>
    <%= "#{@pdf.parent.move.zip} #{@pdf.parent.move.city}" %>
  </p>
</div>

<div class="pdf-greetings-bottom">
  <p>
    Mit freundlichen Grüßen
    <br>
    <%= @pdf.parent.move.user.full_name %>
  </p>
</div>