config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get "about", to: "pages#about"
  
  resources :users
  get 'providers/search', to: 'providers#search'
  resources :providers, only: [ :index, :show, :edit, :update, :destroy ]
  resources :my_providers
  delete "my_providers/unselect/:id", to: "my_providers#unselect"

  resources :moves do
    resources :updates, only: [ :index, :edit ]
  end

  post "start", to: "updates#create_updates"
  post "send", to: "updates#send_updates"
  get "pdfs/:uuid", to: "pdfs#show", as: "pdf"
  get "pdfs/:uuid/mail", to: "pdfs#mail", as: "mail"

  # What's this for? Nicer dashboard URL?
  get '/user' => "my_providers#index", :as => :user_root
end

app/models/my_provider.rb
class MyProvider < ApplicationRecord
  belongs_to :user
  belongs_to :provider

  validates :provider_id, uniqueness: { scope: :user_id, message: "selection must be unique for the user" }
end

app/controllers/my_providers_controller.rb
class MyProvidersController < ApplicationController
  def index
    @my_providers = policy_scope(MyProvider).includes(:provider).order(created_at: :desc)
    @move = current_user.moves.last # Showing the last created move as current
    @updates = @move&.updates # Using the safe navigation operator here, useful in case @move is nil!
    if @move.nil?
      @markers = []
    else
      @markers = [
        {
          lat: @move.latitude,
          lng: @move.longitude
        }
      ]
    end
  end

  def show
    @my_provider = MyProvider.find(params[:id])
    authorize @my_provider
  end

  def create
    @my_provider = MyProvider.new(strong_params)
    authorize @my_provider
    @my_provider.user = current_user

    if @my_provider.save
      respond_to do |format|
        format.html { redirect_to my_providers_path }
        format.json { render json: {}, status: 200 }
      end
    else
      render_errors
    end
  end

  def edit
    @my_provider = MyProvider.find(params[:id])
    authorize @my_provider
  end

  def update
    @my_provider = MyProvider.find(params[:id])
    authorize @my_provider
    @my_provider.update(strong_params)
    redirect_to my_providers_path(checked:"1")
  end

  def destroy
    @my_provider = MyProvider.find(params[:id])
    authorize @my_provider
    @my_provider.destroy
    respond_to do |format|
      format.html { redirect_to my_providers_path }
      format.js {}
    end
  end

  # This one receives requests from the list providers, :id refers to provider
  def unselect
    @my_provider = MyProvider.where(user: current_user, provider_id: params[:id]).first
    authorize @my_provider
    if @my_provider.destroy
      render json: {}, status: 200
    else
      render_errors
    end
  end

  # Maybe we should move it to updates controller, just need to figure out how
  # Checks if all updates are in the new (index 0) status
  def updates_new?
    @updates.nil? || @updates.all? { |update| update.update_status == Update::STATUS[0] }
  end
  helper_method :updates_new?

  private

  def strong_params
    params.require(:my_provider).permit(:provider_id, :identifier_value)
  end

  def render_errors
    respond_to do |format|
      format.html { render :new }  # TODO: add error message
      format.json { render json: @my_provider.errors, status: 400 }
    end
  end
end

app/views/my_providers/_index-buttons.html.erb
<div class="d-flex my-5">
  <%= link_to "1. Plan your move", new_move_path(@my_provider), class: "btn btn-large btn-success mr-3" %>
  <%= link_to "2. Add providers to your list", providers_path, class: "btn btn-large btn-success mr-3" %>
  <%= link_to "3. Send the updates", start_path, method: "POST", class: "btn btn-large btn-success" %>
</div>

app/views/my_providers/_move-info.html.erb
<div class="container container-overview mb-3">

    <div class="text-left pt-3 move align-items-center">

          <h5 class="subtitle"><i class="fas fa-info-circle"></i> Your new address</h5>
          <h5><%= @move.address_string %></h5><br>

          <h5 class="subtitle"><i class="fas fa-calendar-alt"></i>  Your moving date</h5>
          <h5><%= (@move.moving_date).strftime("%A, %d %B %Y") %></h5>


          <div class="mt-3">
            <h6> <%= pluralize( (@move.moving_date - Date.today).to_i, 'Day' ) %> remaining until then!</h6>
          </div>

    </div>


    <div id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>


</div>

app/views/my_providers/_move-status.html.erb
<div class= "my-providers-cards">
  <% @updates.each do |update| %>
    <div class="card-my-status">

        <% if update.provider.logo_url.blank? %>
          <%= image_tag "enterprise.svg" %>
        <% else %>
          <img src="<%= update.provider.logo_url %>">
        <% end %>

      <div class="card-my-status-info">
        <h3> <%= update.provider.name %></h3>
        <p> <%= update.provider.category %></p>
        <p> Status: <%= update.update_status %></p>
      </div>

      <div class="card-my-status-right">
        <h3> Status: </h3>
        <p><%= update.update_status %></p>
      </div>

    </div>
  <% end %>
</div>

app/views/my_providers/_move-updates.html.erb
<div class= "my-providers-cards">
  <% @updates.each do |update| %>
    <div class="card-my-status">

        <% if update.provider.logo_url.blank? %>
          <%= image_tag "enterprise.svg" %>
        <% else %>
          <img src="<%= update.provider.logo_url %>">
        <% end %>

      <div class="card-my-status-info">
        <h5> <%= update.provider.name %></h5>
        <% if update.pdf.present? %>
          <p> 
            <%= link_to pdf_path(update.pdf.uuid) do %>
              Get the letter <%= icon("far", "envelope", class: "text-success") %>
            <% end %>
          </p>
        <% end %>
      </div>

      <div class="card-my-status-right">
        <p>
          <%= "Update #{update.update_status}" %>
          <% case update.update_status %>
          <% when Update::STATUS[1] %>
           <%= icon("fas", "paper-plane", class: "text-info") %>
          <% when Update::STATUS[2] %>
           <%= icon("fas", "thumbs-up", class: "text-success") %>
          <% when Update::STATUS[3] %>
           , please use the <%= icon("fas", "envelope", class: "text-info") %>
          <% when Update::STATUS[4] %>
           <%= icon("fas", "thumbs-up", class: "text-success") %>
          <% end %>
        </p>
      </div>

    </div>
  <% end %>
</div>

app/views/my_providers/_my_pro-section.html.erb
<div class="mt-3 mb-5">
  <%# If we haven't sent the updates (they don't exist or all new), we show all: %>
  <% if updates_new? %>
    <% collapse = "" %>
    <h2>
      Your providers
      <br>
    </h2>
    <hr>
  <% else %>
  <%# If we have any sent updates, we collapse the list and show the button: %>
    <% collapse = "collapse" %>
    <h4>
      Previously added providers
      <button class="btn btn-outline-primary" type="button" data-toggle="collapse" data-target="#providersList" aria-expanded="false" aria-controls="providersList">
      <%= icon("fas", "chevron-circle-right", class: "text-info") %>
      </button>
    </h4>
  <% end %>

  <div class="my-providers-cards mb-3 <%= collapse %>" id="providersList">
    <%= render @my_providers %>
  </div>
</div>

app/views/my_providers/_my_provider.html.erb
<div class="card-my-provider" id='<%= "mp#{my_provider.id}" %>'>

  <%# Must refactor with N+1 request technique %>
  <% if my_provider.provider.logo_url.blank? %>
    <%= image_tag "enterprise.svg" %>
  <% else %>
    <img src="<%= my_provider.provider.logo_url %>">
  <% end %>

  <%# Need to show some notification in case of missing info %>
  <div class="card-my-provider-info">
    <h3> <%= my_provider.provider.name %></h3>
    <p> <%= my_provider.provider.category %></p>
    <% unless my_provider.provider.identifier_name.blank? %>
      <p> 
        <% if my_provider.identifier_value.blank? %>
          Add information:
        <% else %>
          Receives your
        <% end %>
        <%= link_to my_provider.provider.identifier_name, edit_my_provider_path(my_provider) %>
        <%= icon("fas", "exclamation-triangle", class: "text-danger") if my_provider.identifier_value.blank? %>
      </p>
    <% end %>
  </div>

  <div class="card-my-provider-icon">
    <%= link_to my_provider_path(my_provider), method: :delete, remote: true do %>
      <%= image_tag "icons/unchecked.svg" %>
    <% end %>
  </div>

</div>

app/views/my_providers/_new-layout.erb
<div class="tabs-v">

	<input type="radio" name="tabs-v" id="tab1-v">
	<label for="tab1-v">
		<p> 1 . Plan your move </p>
	</label>
	<div class="tab-content">
		<div>
			<div class="txt-tab">
				<div>
					<h3>Where and when do you move? </h3>
					<p>Please let us know your new address and indicate as of when the change should be valid.</p>
					 <%= link_to "Plan your move", new_move_path(@my_provider), class: "btn btn-large btn-success mr-3" %>
				</div>
			</div>
			<div class="img-tab1"></div>
		</div>
	</div>

		<input type="radio" name="tabs-v" id="tab2-v">
	<label for="tab2-v">
		<p> 2 . Add New Providers </p>
	</label>
	<div class="tab-content">
		<div>
			<div class="txt-tab">
				<div>
					<h3>Who do you want to inform? </h3>
					<p>Select all your providers you want to notify. The selection will be saved in your providers list below.</p>
					  <%= link_to "Add new providers", providers_path, class: "btn btn-large btn-success mr-3" %>
				</div>
			</div>
			<div class="img-tab2"></div>
		</div>
	</div>
      
	<input type="radio" name="tabs-v" id="tab3-v" checked="checked">
	<label for="tab3-v">
		<p>3 . Confirm & Send</p>
	</label>
	<div class="tab-content">
		<div>
			<div class="txt-tab">
				<div>
					<h3>Everything is ready?</h3>
					<p>In the last step, please review your data. Everything looks fine? Ready to go! 🎉.</p>
					  <%= link_to "Review your data", start_path, method: "POST", class: "btn btn-large btn-success" %>
				</div>
			</div>
			<div class="img-tab3"></div>
		</div>
	</div>


	</div>

</div>

app/views/my_providers/_new-layout.html.erb
<% checked = params["checked"] == "1" ? "checked" : ""  %>
<% checked_not_present = params["checked"].present? ? "" : "checked"  %>

<div class="tabs-v">

	<input type="radio" name="tabs-v" id="tab1-v" checked="<%= checked_not_present %>">
	<label for="tab1-v">
		<p> 
			1 . Plan your move 
			<% if @move.present? %>
				<%= icon("fas", "check", class: "text-success") %>
			<% end %>
		</p>
	</label>
	<div class="tab-content">
		<div>
			<div class="txt-tab">
				<div>
					<h3>Where and when do you move? </h3>
					<p>Please let us know your new address and indicate as of when the change should be valid.</p>
					 <%= link_to "Plan your move", new_move_path(@my_provider), class: "btn btn-large btn-success mr-3" %>
				</div>
			</div>
			<div class="img-tab1"></div>
		</div>
	</div>

	<input type="radio" name="tabs-v" id="tab2-v">
	<label for="tab2-v">
		<p>
			2 . Add New Providers
			<% if @my_providers.present? %>
				<%= icon("fas", "check", class: "text-success") %>
			<% end %>
		</p>
	</label>
	<div class="tab-content">
		<div>
			<div class="txt-tab">
				<div>
					<h3>Who do you want to inform? </h3>
					<p>Select all your providers you want to notify. The selection will be saved in your providers list below.</p>
					  <%= link_to "Add new providers", providers_path, class: "btn btn-large btn-success mr-3" %>
				</div>
			</div>
			<div class="img-tab2"></div>
		</div>
	</div>
      
	<input type="radio" name="tabs-v" id="tab3-v" <%= checked %>>
	<label for="tab3-v">
		<p>
			3 . Confirm & Send
			<% unless updates_new? %>
				<%= icon("fas", "check", class: "text-success") %>
			<% end %>
		</p>
	</label>
	<div class="tab-content">
		<div>
			<div class="txt-tab">
				<div>
					<h3>Everything is ready?</h3>
					<p>In the last step, please review your data. Everything looks fine? Ready to go! 🎉.</p>
					  <%= link_to "Review your data", start_path, method: "POST", class: "btn btn-large btn-success" %>
				</div>
			</div>
			<div class="img-tab3"></div>
		</div>
	</div>
</div>

app/views/my_providers/destroy.js.erb
console.log('AAAA it works!');

document.getElementById('<%= "mp#{@my_provider.id}" %>').remove();

if (document.querySelector('.card-my-provider') == null) {
  Turbolinks.visit(location.toString());
}

app/views/my_providers/edit.html.erb
<div class="container mt-5">
  <h2> <%= @my_provider.provider.name %> </h2>

  <%= simple_form_for [@my_provider] do |f| %>
    <%= f.input :identifier_value, label: "requires your #{@my_provider.provider.identifier_name}:" %>
    <hr>
    <%= f.submit "Save", class:"btn btn-success" %>
  <% end %>
  
</div>

app/views/my_providers/index.html.erb
<div class="text-above text-center">
  <p> Your dashboard allows you to manage your address change easily. You can start a new change process, save your providers and keep track of the update of your requests.</p>
</div>

<div class="container my-5 block">
  <%= render "new-layout" %>

  <div class="card bg-white rounded-0 border-light mt-3 block p-5">
    <h2> Overview </h2>
    <hr>

    <%# Completely new user will see this: %>
    <% if @my_providers.empty? && @move.nil? %>
      <p> Nothing here yet. <br>Start by <%= link_to "planning your move", new_move_path(@my_provider) %>. </p>
    <% end %>

    <%# If we have the move information, we show the move block: %>
    <% unless @move.nil? %>
      <%= render "move-info" %>
      <%# If we already have some updates planned, we also show the updates block: %>
      <% unless @updates.empty? || updates_new? %>
        <h3 class="mt-3"> Requests sent to providers </h3>
        <hr>
        <%= render "move-updates" %>
      <% end %>
    <% end %>

    <%# If we have any providers selections, we show them: %>
    <% unless @my_providers.empty? %>
      <%= render "my_pro-section" %>
    <% end %>

    <%# A message in case the move is created, but providers are not selected: %>
    <% if @move.present? && @my_providers.empty? && updates_new? %>
      <hr>
      <p> <%= link_to "Select the providers", providers_path %> which you'd like to inform about your new address. </p>
    <% end %>
  </div>
</div>

app/views/my_providers/new.html.erb
<div class="container mt-5">
  <h1> This is the new page </h1>
  <%= render "form" %>
</div>